server:
  port: 9000

email:
  producer:
    appId: suppression-api
  chEmail: ${CH_EMAIL}
  processingDelayEvent: ${PROCESSING_DELAY_EVENT}

# Configure the email-producer library.
kafka:
  broker:
    addr: ${KAFKA_BROKER_ADDR}
  config:
    acks: ${KAFKA_CONFIG_ACKS}
    retries: ${KAFKA_CONFIG_RETRIES}
    isRoundRobin: ${KAFKA_CONFIG_IS_ROUND_ROBIN}

management:
  endpoints:
    web:
      base-path: ''
      path-mapping:
        health: healthcheck

spring:
  data:
    mongodb:
      uri: ${SUPPRESSIONS_API_MONGODB_URL}

suppression:
  payment:
    amount: ${SUPPRESSIONS_PAYMENT_AMOUNT}
